### ISSUE TITLE
Cmake issue building scalar lib with tridcuda_mpi and tridcuda

### ISSUE THREAD

**Issue by benielT** [OP-DSL/tridsolver#19]
Building tridsolver with CUDA 10.2 backend installed. When I tried to make tridsolver/scalar/ I get these errors. 

CMake Error at src/cuda/CMakeLists.txt:94 (add_library):
  Target "tridcuda_mpi" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at src/cuda/CMakeLists.txt:53 (add_library):
  Target "tridcuda" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

NOTE: It seems like CUDA 10.2 do not package with libcublas.so.

**Comment by bgd54** [comment]
Hi!

As far as I know CUDA 10.2 installs with cublas in `/usr/lib64` by default. The library requires cublas to be installed, if it is installed for 10.2 then `find_package(CUDAToolkit)` should find it. Could you check the path for the cublas library?

**Comment by benielT** [comment]
> Hi!
> 
> As far as I know CUDA 10.2 installs with cublas in `/usr/lib64` by default. The library requires cublas to be installed, if it is installed for 10.2 then `find_package(CUDAToolkit)` should find it. Could you check the path for the cublas library?

Hi, 

I added find_package(CUDAToolkit) in the CMakeList.txt as well though it is already checking cuda with check_language(CUDA) in line 88 of CMakeList.txt. "libcublas.so" is inside /usr/lib64/ too. But still, having this error!

To be more specific, it pops up after completing these stages in CMake with -DCMAKE_BUILD_TYPE=Release -DBUILD_FOR_CPU=ON -DBUILD_FOR_GPU=ON -DBUILD_FOR_SN=ON -DBUILD_FOR_MPI=ON flags,

-- The CXX compiler identification is Intel 20.2.4.20210910
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/intel/oneapi/2021.4/mpi/2021.4.0/bin/mpicxx - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_CXX: -qopenmp (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0")  
-- Found MPI_CXX: /opt/intel/oneapi/2021.4/mpi/2021.4.0/bin/mpicxx (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - /opt/cuda/10.2.89/toolkit/bin/nvcc
-- The CUDA compiler identification is NVIDIA 10.2.89
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /opt/cuda/10.2.89/toolkit/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found CUDA: /opt/cuda/10.2.89/toolkit (found version "10.2") 
-- Autodetected CUDA architecture(s):  7.0
-- CUDA_ARCH: 70
-- Found CUDAToolkit: /opt/cuda/10.2.89/toolkit/include (found version "10.2.89") 
-- Configuring done
-- Generating done

**Comment by benielT** [comment]
Hi @bgd54, I have attached the system details and full log of the build with new clone.

### **Requirement verification**
```
benielt@telos:~/libs$ icc --version
icc (ICC) 2021.4.0 20210910
Copyright (C) 1985-2021 Intel Corporation.  All rights reserved.

benielt@telos:~/libs$ echo $MKLROOT
/opt/intel/oneapi/2021.4/mkl/2021.4.0
benielt@telos:~/libs$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
benielt@telos:~/libs$ cmake --version
cmake version 3.20.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
benielt@telos:~/libs$ make --version
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
### **build log**
```
benielt@telos:~/tridsolver/scalar/build$ cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_FOR_CPU=ON -DBUILD_FOR_GPU=ON -DBUILD_FOR_SN=ON -DBUILD_FOR_MPI=ON
-- The CXX compiler identification is Intel 20.2.4.20210910
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/intel/oneapi/2021.4/mpi/2021.4.0/bin/mpicxx - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_CXX: -qopenmp (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0")  
-- Found MPI_CXX: /opt/intel/oneapi/2021.4/mpi/2021.4.0/bin/mpicxx (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - /opt/cuda/10.2.89/toolkit/bin/nvcc
-- The CUDA compiler identification is NVIDIA 10.2.89
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /opt/cuda/10.2.89/toolkit/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found CUDA: /opt/cuda/10.2.89/toolkit (found version "10.2") 
-- Autodetected CUDA architecture(s):  7.0
-- CUDA_ARCH: 70
-- Found CUDAToolkit: /opt/cuda/10.2.89/toolkit/include (found version "10.2.89") 
-- Configuring done
CMake Error at src/cuda/CMakeLists.txt:94 (add_library):
  Target "tridcuda_mpi" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at src/cuda/CMakeLists.txt:53 (add_library):
  Target "tridcuda" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by bgd54** [comment]
Hi,
Could you check also the CMakeCache.txt. It should contain the value for  `CUDA_cublas_LIBRARY` pointing to the .so file.
Does `/opt/cuda/10.2.89/toolkit/include` contains the headers for cublas?

**Comment by benielT** [comment]
`opt/cuda/10.2.89/toolkit/include` contains the headers for cublas. I tried to export CUDA_cublas_LIBRARY in ~/.bashrc with the absolute path to `libcublas.so` but it is vain too.

**Comment by bgd54** [comment]
In the content of `CMakeCache.txt` what is the value for  CUDA_cublas_LIBRARY? Does your `PATH` contains the path to the libcublas.so file?

**Comment by benielT** [comment]
Hi @bgd54,

I tried adding the absolute path to the /opt/cuda/10.2.89/lib64/ to `LD_LIBRARY_PATH` before, but I had a redundant path for copied Cublas libraries. Removing that path and adding the path ` /opt/cuda/10.2.89/lib64/` where `libcublas.so` located to `LD_LIBRARY_PATH` resolved the issue. Thank you for your support.

There's another way to resolve this in the case of having sudo privileges, by adding a symlink inside `opt/cuda/10.2.89/toolkit/lib64/` to link `libcublas*.so` located in a different path. But, I couldn't check it since I don't have sudo privileges.

**Comment by bgd54** [comment]
Hi! 
I'm happy that the issue is resolved. :) Let me know if we can help with anything else. :)
